### ISSUE TITLE
Tested with the current dataset?

### ISSUE THREAD

**Issue by s1998** [tonifuc3m/drugprot-evaluation-library#1]
Hi,

1. I think, we might need a small modification to make this repo work with the Biocreative task 1. The repo assumptions entity type as GENE/CHEMICAL whereas the training dataset I have has entities as GENE-Y/GENE-N/CHEMICAL.
2. Has this been tested with official dataset? It takes too long (> 10 minutes) for me to get the F1 score (not sure if the bug is in my usage or the library). Is this expected? I believe the slow part is calling the f1_score function inside compute_metrics with a very large sparse matrix (570165 * 13 for the training data). 

Regards
Sudhanshu

**Comment by tonifuc3m** [comment]
Hi, Sudhanshu.

Thank you for your email, it helps us improve the evaluation library.

1. Development and Test sets have GENE/CHEMICAL entities. That is why the evaluation repo assumes entities should be either GENE or CHEMICAL. It is not designed to make an evaluation of the training set, but to compute the final participant scores. If you want to do that, the simplest solution would be to substitute in your training set all GENE-Y and GENE-N by GENE.

2. You are right, it is a bit slow at the moment. However, it takes ~60s in my laptop with the official development sets, not > 10 minutes and no issue with sparse matrices. Take into account that both development and test datasets have 750 abstracts. Training dataset has 3500 abstracts. That may be why you have such a huge sparse matrix.
I have modified the preprocessing order to make it a bit more efficient. But what really needs to be done is to optimize the function format_relations() in utils.py to solve this.

**Comment by tonifuc3m** [comment]
Library was tested with dev and test datasets

**Comment by s1998** [comment]
>Development and Test sets have GENE/CHEMICAL entities. That is why the evaluation repo assumes entities should be either GENE or CHEMICAL. It is not designed to make an evaluation of the training set, but to compute the final participant scores. If you want to do that, the simplest solution would be to substitute in your training set all GENE-Y and GENE-N by GENE. 

Understood.

> You are right, it is a bit slow at the moment. However, it takes ~60s in my laptop with the official development sets, not > 10 minutes and no issue with sparse matrices.

I meant it took > 10 minutes for the training data.

Thank you for the fast reply, clears everything.
